#!/usr/bin/env python2

from gradelib import *

r = Runner()

def matchtest(parent, name, points, *args, **kw):
    def do_test():
        r.match(*args, **kw)
    test(points, name, parent=parent)(do_test)

@test(5, "assignment [part1.c]")
def test_part1():
    r.run_test("build/part1")
    r.match("part1: OK")

@test(5, "swap [part2.c]")
def test_part2():
    r.run_test("build/part2")
    r.match("part2: OK")

@test(5, "array sum [part3.c]")
def test_part3():
    r.run_test("build/part3")
    r.match("part3: OK")

@test(0, "point structure [part4.c]")
def test_part4():
    r.run_test("build/part4")
matchtest(test_part4, "set_point", 5, "part4: set_point OK")
matchtest(test_part4, "point_dist", 5, "part4: point_dist OK")

@test(0, "linked list [part5.c]")
def test_part5():
    r.run_test("build/part5")
matchtest(test_part5, "list_insert", 5, "part5: list_insert OK")
matchtest(test_part5, "list_end", 5, "part5: list_end OK")
matchtest(test_part5, "list_size", 5, "part5: list_size OK")
matchtest(test_part5, "list_find", 5, "part5: list_find OK")
matchtest(test_part5, "list_remove", 5, "part5: list_remove OK")

run_tests()
